apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: cluster-1
    devEnvApprovers:
    - umairbajwa
    environmentGitOwner: umairbajwa
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "457821620142"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: diesel-charge-372420
    provider: gke
    registry: gcr.io
    zone: europe-west2-b
  environments:
  - key: dev
    owner: umairbajwa
    repository: jx3-gke
  - key: staging
  - key: production
  ingress:
    domain: umairbajwa.net
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: umairbajwa
  repository: nexus
  secretStorage: gsm
  vault: {}
  webhook: lighthouse
